import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Alfa_Slab_One, Dela_Gothic_One, Rubik_Doodle_Shadow, Special_Elite, Vollkorn } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const alfaSlabOne = Alfa_Slab_One({ 
  weight: "400",
  subsets: ["latin"],
  variable: "--font-alfa-slab-one"
});

const delaGothicOne = Dela_Gothic_One({ 
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dela-gothic-one"
});

const rubikDoodleShadow = Rubik_Doodle_Shadow({ 
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rubik-doodle-shadow"
});

const specialElite = Special_Elite({ 
  weight: "400",
  subsets: ["latin"],
  variable: "--font-special-elite"
});

const vollkorn = Vollkorn({ 
  weight: "400",
  subsets: ["latin"],
  variable: "--font-vollkorn"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${alfaSlabOne.variable} ${delaGothicOne.variable} ${rubikDoodleShadow.variable} ${specialElite.variable} ${vollkorn.variable}`}>
        {children}
      </body>
    </html>
  );
}

import "./globals.css";
